export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#6d3000',
        'secondary-container': '#feb700',
        'primary-fixed': '#c6e7ff',
        'on-secondary-fixed': '#271900',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eeeef0',
        surface: '#f9f9fc',
        'on-secondary-container': '#6b4b00',
        secondary: '#7c5800',
        'tertiary-container': '#ff9249',
        'on-background': '#1a1c1e',
        'primary-container': '#00baff',
        'inverse-primary': '#81cfff',
        primary: '#00658d',
        'surface-container-low': '#f3f3f6',
        'tertiary-fixed': '#ffdbc8',
        'on-tertiary-fixed-variant': '#753400',
        'on-primary-container': '#004764',
        'on-error': '#ffffff',
        'on-surface-variant': '#3d4850',
        'outline-variant': '#bdc8d2',
        outline: '#6d7881',
        'on-tertiary-fixed': '#321200',
        'secondary-fixed-dim': '#ffba20',
        'primary-fixed-dim': '#81cfff',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'inverse-on-surface': '#f0f0f3',
        'surface-dim': '#dadadc',
        'on-surface': '#1a1c1e',
        'tertiary-fixed-dim': '#ffb68b',
        'on-primary-fixed': '#001e2d',
        'on-secondary-fixed-variant': '#5e4200',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'secondary-fixed': '#ffdea8',
        tertiary: '#994700',
        'inverse-surface': '#2f3133',
        'on-secondary': '#ffffff',
        background: '#f9f9fc',
        'on-primary-fixed-variant': '#004c6b',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f9f9fc',
        'on-error-container': '#93000a',
        'surface-tint': '#00658d',
        'surface-variant': '#e2e2e5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        xl2: '1.25rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'container-max': '1200px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(0, 101, 141, 0.08)',
        'glow': '0 0 25px -5px rgba(0, 186, 255, 0.3)',
        'card-hover': '0 12px 30px -10px rgba(0, 101, 141, 0.12)',
      },
    },
  },
  plugins: [],
}
